# 1. What is Numpy?
<small>and how to use it? </small>

- numpy는 <b>"numerical python"</b>의 약자입니다.
> Numerical computing : 컴퓨터가 실수값을 효과적으로 계산할 수 있도록 하는 연구 분야.
> Vector Arithmetic : 벡터 연산 --> 데이터가 벡터로 표현되기 때문이다.

- numpy는 다양한 머신러닝 라이브러리들에 의존성을 가지고 있고, 일반 파이썬 리스트에 비해 강력한 성능을 자랑합니다.
> 성능 : numpy array >> python list(or tiple)

- python list와 비슷한 개념을 numpy에서는 **numpy array**라고 부른다.
> 파이썬 리스트처럼 여러 데이터를 한번에 다룰 수 있으나, 모든 데이터가 동일한 data type을 가져야합니다.

- C언어와 JAVA에서 사용하는 array와 비슷한 개념이며, 동적 할당(dynamic type binding)을 지원하는 파이썬의 리스트와 구조가 다릅니다.


- Numpy의 특징
<br>
<br>

**1) numpy array는 모든 원소의 자료형이 동일해야 한다.**

(아래는 numpy array가 지원하는 data types)

![numpy_data_type](../images/numpy/numpy_datatypes.png)

**2) numpy array는 선언할 때 크기를 지정한 뒤, 변경할 수 없다. list.append(), pop()을 통해 자유롭게 원소 변경 및 크기 변경이 가능하지만, numpy array는 만들어지고 나면 원소의 update는 가능하지만, array의 크기를 변경할 수는 없다.**

> numpy의 경우에는 append라는 함수가 있으나, 의미가 다르다.

> numpy array를 변경하는 경우에는 복사가 일어난다


**3) 사실 numpy array는 C, C++로 구현이 되어 있다. 이는 high performance를 내기 위해서이며, python이 Numerical computing에 취약하다는 단점을 보완한다.**

(아래 예시는 C언어와 파이썬의 코드 비교)

```C
/* C 코드 */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

```python
# 파이썬 코드
result = 0
for i in range(100):
    result += i
```

**4) numpy array가 python list보다 빠른 이유 중에 하나는 원소의 type checking을 할 필요가 없기 때문이다.**

(아래 예시를 보자)

```C
/* C 코드 */
int x = 4;
x = "four";  // 실패
```
-> It is called, "Static type binding"



```python
# 파이썬 코드
x = 4
x = "four"
```

-> It is called, "Dynamic type binding"

(python list와 numpy array의 내부 구현 비교)

![Integer Memory Layout](../images/numpy/cint_vs_pyint.png)

![Array Memory Layout](../images/numpy/array_vs_list.png)

<small> (Source from Data Science Handbook) </small>

**5) numpy array는 universal function(through broadcast)를 제공하기 때문에 같은 연산 반복에 대해 훨씬 빠르다. 데이터의 크기가 클수록 차이가 더 크다.**

- 아래는 big_array라는 1000000개의 원소를 가지는 array를 만든 뒤에 for문을 돌면서 각 원소를 뒤집는 연산을 했을 때의 걸리는 시간과, numpy array에 있는 UFuncs(Universal function)을 사용했을 때 걸리는 시간을 측정한 것이다.


- 거의 1000배정도 차이가 나는 것을 볼 수 있다.

![speed_comparison](../images/numpy/list_vs_nparray.png)

# 2. Numpy Basics 

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

## 2.1 Numpy array Creation

In [1]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [2]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4, 5]
data, type(data)

([1, 2, 3, 4, 5], list)

In [4]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [
        [1, 2, 3,],
        [4, 5, 6,],
        [7, 8, 9 ]
]
data2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# 파이썬 list를 numpy array로 변환합니다.
arr1 = np.array(data)
arr1, type(arr1)
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
np.array([1, 2, 3, 4, 5]) #ok
np.array((1, 2, 3, 4, 5))
arr1.shape # np.array.shape은 np.array의 크기를 알려줍니다.
# 5 x 1 (5, )

In [6]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2)
arr2, type(arr2)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

In [8]:
arr2.shape
print("arr2의 ndim :", arr2.ndim) # arr2의 차원
print("arr2의 shape :", arr2.shape) # arr2의 행, 열의 크기
print("arr2의 size : ", arr2.size) # arr2의 행 x 열
print("arr2의 dtype : ", arr2.dtype)# arr2의 원소의 타입. # int64 : integer + 64bits
print("arr2의 itemsize : ", arr2.itemsize) # arr2의 원소의 사이즈(bytes) # 64bits = 8B
print("arr2의 nbytes : ", arr2.nbytes) # itemsize * size # numpy array가 차지하는 메모리 공간.

arr2의 ndim : 2
arr2의 shape : (3, 3)
arr2의 size :  9
arr2의 dtype :  int32
arr2의 itemsize :  4
arr2의 nbytes :  36


## 2.2 Array Initialization 

- numpy array를 초기값과 함께 생성하는 방법도 있습니다.


- 원소가 0인 array를 생성하는 np.zeros()

- 원소가 1인 array를 생성하는 np.ones()

- 특정 범위의 원소를 가지는 np.arange()

In [9]:
# 0이 5개 있는 array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
# 0이 3x3인 array
#np.zeros(3,3) #에러남
np.zeros((3,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# 1이 3개 있는 array
np.ones(3)

array([1., 1., 1.])

In [12]:
# 1이 2x2인 array
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(10) # np.array(list(range(10)))

In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array
np.arrange(10, 100) # python range 함수와 동일한데, np.arrange 생성까지 자동으로 해줌

## 2.3. Array Operation (like vector) --> Universal Function

- numpy array를 쓰는 가장 큰 이유는 vector처럼 사용할 수 있기 때문입니다.
> e.g. arr1 = np.array([1, 2, 3, 4, 5]) --> (1, 2, 3, 4, 5) # vector

- 그렇기 때문에 scipy, matplotlib, scikit-learn, pandas, tensorflow, pytorch 등 대부분의 데이터분석 라이브러리들이 numpy array를 사용합니다.
> 대부분의 데이터 분석 라이브러리들은 벡터를 사용하는데, 그 벡터가 바로 numpy array로 표현되기 때문입니다.


- 데이터 분석은 99.9% 데이터를 벡터로 표현하여 분석하기 때문에, 이 특징은 ***굉장히*** 중요합니다.
> 벡터 == numpy array

> 3blue1brown 가시면 참고하기 좋은 영상들 있음

![Vector operation](../images/numpy/vector_operations.png)

- 두 벡터 A = (1, 2), B = (2, 1)이라고 할 때, 벡터의 연산은 다음과 같이 정의됩니다.

A + B = (3, 3)


A - B = (-1, 1)


A o B = 1x2 + 2x1 = 4 (dot product)

![Vector product](../images/numpy/vector_product.png)

In [14]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array((1, 2, 3,))
v2 = np.array((4, 5, 6,))
type(v1), type(v2)

(numpy.ndarray, numpy.ndarray)

In [15]:
# 튜플로 더하기 연산해보기
t1 = (1, 2, 3)
t2 = (4, 5, 6)
#type(t1), type(t2)
t1 + t2

(1, 2, 3, 4, 5, 6)

In [16]:
#  vector addition
v1 + v2
#이 과정이랑 같음
L = []
for x, y in zip(v1, v2):
    a = x - y
    L.append(a)
L

array([5, 7, 9])

In [17]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [18]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [19]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [ ]:
# dot product
v1 @ v2 # 1x4 + 2x5 + 3x6  

## 2.4. Broadcast

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [20]:
arr1 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [21]:
arr1.shape

(2, 3)

In [22]:
arr2 = np.array([7, 8, 9])

In [23]:
arr2.shape

(3,)

In [24]:
# 2개의 array를 더해보면?
arr1  + arr2  #[1, 2, 3] + [7, 8, 9] // [4, 5, 6] + [7, 8, 9]

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2 # [1, 2, 3] * [7, 8, 9] // [4, 5, 6] * [7, 8, 9]
#[1, 2, 3] x [7]
#[4, 5, 6] x [8]
#            [9]

In [25]:
# arr1에 10을 곱해보면?
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [27]:
# arr1을 제곱해보면?
arr1 * arr1

array([[ 1,  4,  9],
       [16, 25, 36]])

## 2.5. Universal Functions 

- numpy array는 하나의 함수를 모든 원소에 자동으로 적용해주는 Universal Function이라는 기능을 제공한다. 이 덕분에 모든 원소에 대해 같은 작업을 처리할 때 엄청나게 빠른 속도를 낼 수 있다.

In [28]:
arr1 = np.array([1, 2, 3])
arr1 / 1

array([1., 2., 3.])

In [30]:
# 모든 원소를 역수를 취하려면 어떻게 해야할까?
1 / arr1 # 각 원소에 1 / 라는 operation을 모두 적용하는 연산이 됩니다

array([1.        , 0.5       , 0.33333333])

In [29]:
# 모든 원소에 2를 더하려면 어떻게 해야할까?
arr1 + 2

array([3, 4, 5])

## 2.6. Indexing (same as python list, but more powerful) 

In [ ]:
arr1 = np.arange(10)
arr1

In [ ]:
# 첫번째 원소


In [ ]:
# 마지막 원소


In [ ]:
# 앞에서부터 원소 3개 slicing


In [ ]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

In [ ]:
# arr2의 2, 3 원소 = 7


In [ ]:
# arr2의 세번째 columnm (3, 7, 11)


In [ ]:
# arr2의 두번째 row


## 2.7. Masking 

In [ ]:
mask = np.array([1, 0, 0, 1, 1, 0, 0])
mask

In [ ]:
data = np.random.randn(7, 4)
data

In [ ]:
data.shape

In [ ]:
# mask 만들기


In [ ]:
# 위에서 생성한 data에 mask를 적용해본다.


In [ ]:
# 마스크를 0으로 바꿔본다.


In [ ]:
# fancy indexing을 이용해서 masking



In [ ]:
# fancy indexing의 또 다른 방법
data[data[:, 0]<0, 0]

In [ ]:
# 2차원 data에서 첫번째 column에 0보다 작은 원소들을 0으로 치환해주세요.


## 2.8. Numpy Methods 

In [ ]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.


In [ ]:
# mat1에 절대값 씌우기


In [ ]:
# mat1의 square root(제곱근) 구하기


In [ ]:
# mat1 제곱하기


In [ ]:
# mat1의 지수값 구하기


In [ ]:
# mat의 log값(자연로그) 구하기


In [ ]:
# 상용로그


In [ ]:
# 이진로그


In [ ]:
# 부호찾기


In [ ]:
# 올림


In [ ]:
# 내림


In [ ]:
# 존재하지 않는 값이 있는지 없는지 # nan = not a number


In [ ]:
np.isnan(np.log(mat1))

In [ ]:
np.isinf(mat1)

In [ ]:
np.sin(mat1)

In [ ]:
np.cos(mat1)

In [ ]:
np.tan(mat1)

In [ ]:
np.tanh(mat1)

In [ ]:
mat2 = np.random.randn(5, 3)
mat2

In [ ]:
np.maximum(mat1, mat2)

## 2.9. Reshaping array

In [ ]:
x = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
x

In [ ]:
# x를 3x3 행렬로 변형합니다.


In [ ]:
x == x1

In [ ]:
# (1, 2, 3)을 transpose 해봅니다.



## 2.10. Concatenation of arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1와 arr2를 합칩니다
# arr1 + arr2?


In [ ]:
# stacking vertically


In [ ]:
# stacking horizontally


## 2.11. Aggregation functions 

In [ ]:
mat1

In [ ]:
 # 15개 숫자의 총합.

In [ ]:
# 다른 축으로 더해보기


In [ ]:
# 다른 축으로 더해보기


In [ ]:
# 평균


In [ ]:
mat3 = np.random.rand(5, 3)
mat3

In [ ]:
np.mean(mat3)

In [ ]:
np.mean(mat3, axis=0)

In [ ]:
np.mean(mat3, axis=1)

In [ ]:
np.std(mat3) # 표준편차

In [ ]:
np.min(mat3, axis=0)

In [ ]:
np.max(mat3, axis=1)

In [ ]:
# 최소값이 있는 Index
np.argmin(mat3, axis=0)

In [ ]:
# 최대값이 있는 Index
np.argmax(mat3, axis=1)

In [ ]:
np.cumsum(mat3)

In [ ]:
np.cumsum(mat3, axis=1) # row별 누적합.

In [ ]:
np.cumprod(mat3, axis=0)

In [ ]:
# 그냥 정렬
np.sort(mat3)

In [ ]:
# index를 정렬
np.argsort(mat3, axis=0) # argument sorting에서 정렬된 값의 원래 위치를 보여줍니다.
# 정렬된 다음의 index를 원래 원소의 위치에 표시해줍니다.

## 3. Powerful Numpy 

- 맨 처음에도 봤듯이 numpy array는 파이썬 리스트에 비해 연산이 빠릅니다.
> broadcast, static type binding, fixed array size, ... --> vectorize
> 조건 : 원소의 개수가 많을 때.

- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [ ]:
np.random.seed(0)

# Numpy array의 각 원소의 역수를 취하는 함수.
def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

# Numpy array의 모든 원소의 합을 구하는 함수.


In [ ]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, size=1000000)

In [ ]:
big_array.shape

In [ ]:
%timeit reverse_num(big_array)

In [ ]:
%timeit 1.0 / big_array

In [ ]:
%timeit

In [ ]:
%timeit

### Q. 왜 numpy가 파이썬(정확히는 CPython)으로 구현한 함수를 통해 반복문을 수행한것보다 빠를까?

A1. 매번 반복할 때마다 ***"type matching"*** 과 ***"function dispatching"*** 을 파이썬 interpreter가 수행하기 때문에 **"performance bottleneck"** 이 생깁니다.

A2.