# 재귀 함수

In [ ]:
def recursive_func():
    print("나는 재귀함수다!!")
    recursive_func()

# 재귀 함수 실행  --> 무한루프 시행(파이썬은 몇 번 부르다가 잘라냄)
recursive_func()

In [1]:
def my_factorial(n):
# 진짜 불러지는지 확인을 위해서 print 함수를 사용을 함..
    print("My Factorial 불렀으? n값은?" + str(n))
    if n <= 1 :
        return 1
    else:
        return  n * my_factorial(n - 1)

### 실제 4!에 대한 계산 시행
my_factorial(4)

My Factorial 불렀으? n값은?4
My Factorial 불렀으? n값은?3
My Factorial 불렀으? n값은?2
My Factorial 불렀으? n값은?1


24

In [5]:
#4!의 값을 구하는 코드 작성
n = 4
fact = 1
#1) for문 : 직접적으로 필요한 수를 만들어서 그 값들을 직접 돌리는 구조
for i in range(1,n+1,1):  #요기서 필요한 것은 1,2,3,4숫자 -> range
    fact *= i
    
#2) while문 : 주로 조건 만족할 때까지 돌리는 구조
#             조건 잘 설정 -> 종료할 수 있게
a =1 # 증가용, n의 값 변경 안하려고
while a <= n: # 주어진 n보다 크면 더 안하게
    fact *= a #필요한 숫자 1을 기준으로 +1 하면서 생성 & 반복
    a += 1

In [6]:
#종료 조건 추가하기

In [7]:
#명시적으로 몇 번 반복을 할지를 입력으로 받아서
#부를 때마다 +1 하면서 그 수가 50이 되면
#종료하기 위해서 -> 빠져나갈 퇴로 만들어 둠
def recursive_func(i):
    if i == 50:
        return
    else:
        print("나는 {}번째 Call".format(i))
        recursive_func(i + 1)
# 재귀 함수 실행 
recursive_func(1)

나는 1번째 Call
나는 2번째 Call
나는 3번째 Call
나는 4번째 Call
나는 5번째 Call
나는 6번째 Call
나는 7번째 Call
나는 8번째 Call
나는 9번째 Call
나는 10번째 Call
나는 11번째 Call
나는 12번째 Call
나는 13번째 Call
나는 14번째 Call
나는 15번째 Call
나는 16번째 Call
나는 17번째 Call
나는 18번째 Call
나는 19번째 Call
나는 20번째 Call
나는 21번째 Call
나는 22번째 Call
나는 23번째 Call
나는 24번째 Call
나는 25번째 Call
나는 26번째 Call
나는 27번째 Call
나는 28번째 Call
나는 29번째 Call
나는 30번째 Call
나는 31번째 Call
나는 32번째 Call
나는 33번째 Call
나는 34번째 Call
나는 35번째 Call
나는 36번째 Call
나는 37번째 Call
나는 38번째 Call
나는 39번째 Call
나는 40번째 Call
나는 41번째 Call
나는 42번째 Call
나는 43번째 Call
나는 44번째 Call
나는 45번째 Call
나는 46번째 Call
나는 47번째 Call
나는 48번째 Call
나는 49번째 Call


# 탐색 알고리즘

### DFS에 대한 부분

In [8]:
#인접 리스트로 표현
graph = {
    "1" : ["2","3","8"],
    "2" : ["1","7"],
    "3" : ["1","4","5"],
    "4" : ["3","5"],
    "5" : ["3","4"],
    "6" : ["7"],
    "7" : ["2","6","8"],
    "8" : ["1","7"]
}
graph

{'1': ['2', '3', '8'],
 '2': ['1', '7'],
 '3': ['1', '4', '5'],
 '4': ['3', '5'],
 '5': ['3', '4'],
 '6': ['7'],
 '7': ['2', '6', '8'],
 '8': ['1', '7']}

In [12]:
def dfs_list(graph, start): #입력 : 지도 - 인접 리스트 방식
    #우선 필요한 변수  : 방문할 곳, 방문한 곳  -> 리스트로
    need_visit = list()
    visited = list()
    #일단 시작노드에서 출발 -> 입력 start
    need_visit.append(start)
    #이제부터 본격적으로 해야할 일
    #큰 틀 : need_visit가 없을 때 까지
    while need_visit: # 조건에 리스트 -> 빈 것이면 false 
        #to visit list에서 일단  1개씩 꺼내서 이동
        node = need_visit.pop() # 방문리스트 중 맨 뒤 선택
        #잠시 지금 node가 과거 방문한 곳인이 아닌지 체크
        #     --> 지금 node가 처음 온 상태
        if node not in visited:  #방문 목록에 없으면
            #새로운 곳에 왔으니 도장 찍기
            visited.append(node)
            #지금 여기서 연결된 곳들을 -> to visit list 추가
            need_visit.extend(graph[node])
    return visited
            

In [10]:
dfs_list(graph, "1")

['1', '8', '7', '6', '2', '3', '5', '4']

In [ ]:
#그러면 탐색의 순서를 연결되 노드 중에서 제일 작은 값을 우선으로 방문하려면...?
#graph를 내가 작은 -> 큰걸로 작성해서 큰 노드 우선 pop해서 탐색
# need_visit.extend(graph[node])를 뒤집어야 함
temp = graph[node] # -> [2,3,8] 
temp_reverse = list(reversed(temp)) # -> [8,3,2]

need_visit.extend(temp_reverse)

In [14]:
#값들을 좀 더 빠르게 추가하고, 빼내기 위해
#deque라는 외부 패키지를 활용할 자료구조 사용

In [15]:
from collections import deque 

In [16]:
test_deq = deque()
test_deq.append("a")
test_deq

deque(['a'])

In [17]:
test_deq.append("b")
test_deq

deque(['a', 'b'])

In [18]:
test_deq.appendleft("c")
test_deq

deque(['c', 'a', 'b'])

In [19]:
test_deq.pop()

'b'

In [20]:
test_deq.popleft()

'c'

In [21]:
test_deq
#deque 결론 : 쌩 파이썬의 list와 기능이 동일 + 다만 앞쪽(left) 원소 추가, 제거를 명시적으로 
# --> 원소를 추가/제거시 속도 향상

deque(['a'])

In [22]:
#DFS에서 Stack을 쌩 파이썬의 list로 구현하지 않고
#collections 패키지의 deque를 활용해서 stack으로 활용

In [ ]:
#사용하기 전에는 반듯이 해당 패키지 불러야 함
#부르기 전에는 collectons 패키지가 설치가 되어 있어야 함
# --> 아나콘다, programmers 등은 기본으로 사용 할 수 있는 패키지임
from collections import deque  

In [23]:
def dfs_deque(graph, start): 
    #쌩 파이썬list, deque 동일하다는 것으로 보여주기 위해 하나만 deque로 바꿈
    need_visit = deque() #앞에 코드와 동일 요기만 다름!
    visited = list()
    need_visit.append(start)
    #이제부터 본격적으로 해야할 일
    #큰 틀 : need_visit가 없을 때 까지
    while need_visit: 
        node = need_visit.pop() 
        if node not in visited:  
            visited.append(node)
            temp = graph[node] # -> [2,3,8] 
            temp_reverse = list(reversed(temp)) # -> [8,3,2]
            need_visit.extend(temp_reverse)
    return visited

In [25]:
dfs_deque(graph, "1")

['1', '2', '7', '6', '8', '3', '4', '5']

In [26]:
#DFS를 그러면 Stack으로 활용해서 하는데 
#-> 계속 동일한 일은 하는데 이것을 함수로 하면..?

In [27]:
#전체 지도, 지금 위치, 지금까지 간 곳들 목록(visited)
#이 기능을 언제 불러요? -> 지금 위치가 new하면
def def_recursive_dict(graph, start,visited = [] ): 
    #일단 지금 위치 도장
    visited.append(start)
    #
    for node in graph[start]:
        if node not in visited:
            def_recursive_dict(graph, node, visited)
    return visited
    

In [29]:
def_recursive_dict(graph, "1")

['1', '2', '7', '6', '8', '3', '4', '5']

## 얼음 덩어리 문제

In [32]:
# step1) 얼음 덩어리 입력단 설계
##입력 1번째 줄 처리
n,m = map(int,input("가로, 세로를 공란으로 입력하세요 ").split())
##입력 2번째 줄부터 마지막줄까지 얼음틀 정보 입력
graph = []
for _ in range(n): # n개의 가로줄 입력 받기 위해서... 반복
    graph.append(list(map(int,input("정보 입력하세요").split())))
graph

가로, 세로를 공란으로 입력하세요 4 5
정보 입력하세요0 0 1 1 0
정보 입력하세요0 0 1 1 1
정보 입력하세요1 1 1 1 1
정보 입력하세요0 0 0 0 0


[[0, 0, 1, 1, 0], [0, 0, 1, 1, 1], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0]]

In [35]:
graph[0][0]

1

In [36]:
#DFS로 구현할 때 가장 큰 틀은 counting

#각 포인트마다 이동하면서 할 일이 동일함 -> 결과가 go, stop
#--> 입력 : 위치정보, 출력 : go/ stop -> True, False
def dfs_ice(x,y):
    #얼음 틀 밖이면 더 call 안해도 된다
    if x <= -1 or x >= n or y >= m or y <= -1:
        return False
    #얼음 틀 안이면, 그 현재 위치가 0이면 이동시켜 보자
    if graph[x][y] == 0:
        #일단 x,y에서 0이라고 해서 시작한다 -> 왔다 
        graph[x][y] = 1
        # --> L, R, U, D하면서 위에서 한 일 -> 도장 찍기
        dfs_ice(x-1,y) #Up
        dfs_ice(x+1,y) #Down
        dfs_ice(x,y+1) #Right
        dfs_ice(x,y-1) #Left
        return True
    return False
        
        
result = 0 
for i in range(n):
    for j in range(m):
        if dfs_ice(i,j) == True: #더 이상 움직이지 못 하면
            result += 1

In [37]:
result

2

# Numpy

>패키지가 일단 설치 되어있다는 전제하에  패키지 부를 때                                      
>1)패키지 전체를 부르는 경우
import numpy 
/ import numpy as np                                         
>2)패키지 중 일부만 부를 때
  from 사용할 패키지 import 내가 필요한 것만

 * 1) 벡터 연산 -> 모든 원소에 일괄 적용!!!!
                    -> 수식적인 표현을 그대로 코드로
                    ->조건 검색이 가능한 불리언 인덱싱!
                    ->데이터에 대해서 엄격하게 차원 (오/열 딱 각져야 함) ->ndim, shape, dtype
                       --> 차원을 포함하여 reshape가능 (단, 차원 유지)
                    ->수치연산 : 여러 수학적 함수가 사전에 정의가 되어 있음 -> 필요한 함수 검색해서 사용 
                    
* 2) 속도 -> 속도가 빠른데, 이유는 내부적인 메모리 

* 3) 기타(인덱스) : 리스트 처럼 생각 -> 차원, 가로/세로의 관점으로 인덱스 접근
                                         -> 가로/세로에 정수, 슬라이싱, 조건

In [38]:
a = [100,200,300,400,500]
# -> [110,210,310,410,510]

In [39]:
b = []
for i in a:
    b.append(i + 10)
print(b)

[110, 210, 310, 410, 510]


In [40]:
[ i + 10 for i in a]

[110, 210, 310, 410, 510]

In [44]:
import numpy as np
a_arr = np.array(a)
a_arr

array([100, 200, 300, 400, 500])

In [45]:
a_arr + 10 # x + 10
# ---> 벡터 표현이 가능하여 수식을 그대로 코드로
#      적용이 간단하다!!!

array([110, 210, 310, 410, 510])

In [46]:
# 위의 경우와 유사한데...
# 수학적 표현이라고 하면,,
x = [1,2,3,4,5]
y = [10,20,30,40,50]
# -> x+y = [1+10, 2+20, 3+30, 4+40, 5+50]

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [47]:
# Q)위의 쌩 파이썬의 리스트를 가지고 벡터합을 구현하려면?
z = []
for i in range(len(x)):
    z.append(x[i] + y[i])
z

[11, 22, 33, 44, 55]

In [49]:
x_arr = np.array(x)
y_arr = np.array(y)
print(x_arr)
print(y_arr)

[1 2 3 4 5]
[10 20 30 40 50]


In [50]:
x_arr + y_arr
#두 벡터의 합으로 코드가 동일하게 작성

array([11, 22, 33, 44, 55])

### array 생성

In [52]:
test_arr = np.array([1,2,3,4,5,["a","b","c",12,3]])
test_arr

C:\Users\MEDICI\AppData\Local\Temp/ipykernel_189632/864172562.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  test_arr = np.array([1,2,3,4,5,["a","b","c",12,3]])


array([1, 2, 3, 4, 5, list(['a', 'b', 'c', 12, 3])], dtype=object)

### array의 기본 정보

In [58]:
a = np.array([
             [1,2,3],
             [4,5,6]
                  ])
print(a.ndim) # 몇 차원인지
print(a.shape) # 00000000000데이터 모양
print(a.dtype) # 값들이 정수, 실수, 문자인지

2
(2, 3)
int32


In [59]:
## array에서 원하는 값을 접근하기 위해서는?
# -> 리스트와 동일!!! 정수 인덱스가 기본
#                     슬라이싱

In [60]:
a = [1,3,5,10]
a_arr = np.array(a)
a_arr

array([ 1,  3,  5, 10])

In [61]:
a_arr[2]

5

In [62]:
a_arr[:]

array([ 1,  3,  5, 10])

In [63]:
a_arr[::2]

array([1, 5])

### 입력할 때 데이터 타입 지정

In [65]:
b = [1,2,3]
b_arr = np.array(b, dtype = np.string_)
b_arr

array([b'1', b'2', b'3'], dtype='|S1')

In [ ]:
#데이터 타입 변경(수정)
bb_arr = b_aarr.astype(np.float64) #np를 사용하니 np가 지정한 타입
bb_arr

In [66]:
## range vs arange 함수  : 시작점, 끝점, 간격 다 똑같음

In [67]:
for i in range(5): 
    print(i)

0
1
2
3
4


In [68]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


### 기본적인 수치연산에 많이 사용하는 것들                                    
->선형대수에서 사용하는 특수한 행렬들이 필요하며

In [70]:
np.ones(4)

array([1., 1., 1., 1.])

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 6 by 6 matrix에서 인덱스 문제

In [74]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [78]:
a = np.arange(0,51,10)[:, np.newaxis] + np.arange(0,6,1) #np.newaxis 축 뒤집음
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [80]:
a[0][3]

3

In [81]:
a[0,3] #다이렉트로 접근 가능 

3

In [82]:
a[0:3:2,3:5]

array([[ 3,  4],
       [23, 24]])

In [83]:
a[[0,4]] #맨 외각의 [  ]인데스를 쓰겟다의 기호
#그 안의 [  ] 의 내가 볼 인덱스가 여러개여서
#리스트로 보고자 한느거 다 써서 던진 리스트 표현

array([[ 0,  1,  2,  3,  4,  5],
       [40, 41, 42, 43, 44, 45]])

In [87]:
red = a[:,2]
red

array([ 2, 12, 22, 32, 42, 52])

In [86]:
orange = a[0,3:5]
orange

array([3, 4])

In [92]:
baby_green = a[2::2, ::2]
baby_green

array([[20, 22, 24],
       [40, 42, 44]])

In [89]:
green = a[4:, 4:]
green 

array([[44, 45],
       [54, 55]])

### boolean indexing

>인덱스를 사용하는데 정수가 아니라 논리적인 인덱스를 사용하겠다

In [93]:
test_arr = np.arange(10)
test_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
#예시 상황1) 1000개의 위의 test_arr, 값도 랜덤
# --> 5보다 작은 값은 뭘까?
test_arr < 5 

array([ True,  True,  True,  True, False,  True,  True, False, False,
       False,  True,  True, False, False])

In [101]:
#그래서 궁극적으로 전체 데이터 중에서 
#실제 5보다 작은 값들이 누구냐? 정체를 나타내라
test_arr[test_arr < 5]

array([1, 2, 3, 4, 3, 2, 2, 3])

In [109]:
#예를 들어 3~5사이의 값들만 보고 싶다
# -> 위의 데이터에서 3,4,5에 해당하는 값들만 보고 싶음
#--> 조건1 : 3이상, 조건2 : 5이하, 조건1과 2는 and
test_arr = np.array([1,2,3,4,5,3,2,6,8,9,2,3,5,6])
print(test_arr[ (test_arr >= 3) & (test_arr <= 5)])
print(len(test_arr[ (test_arr >= 3) & (test_arr <= 5)]))

[3 4 5 3 3 5]
6


### 나머지 기타 등등

In [111]:
a = np.arange(32)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [112]:
a.reshape((4,8)) #오와 열이 맞아야 함

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [113]:
#수치엱산을 위한 것들이니 필요한 여러 연산을 미리 정의

In [114]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [115]:
a.mean()

15.5

In [116]:
a.std()

9.233092656309694