<a href="https://colab.research.google.com/github/yeonji0-0/Python-codes/blob/main/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98_%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.__version__

'2.7.0'

In [ ]:
# 1 by 1  (1차원 벡터)

In [ ]:
x = tf.Variable(np.array([ [1] ]), dtype = tf.float32)
x

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[1.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
b

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [ ]:
print(A.shape)
print(x.shape)
print(b.shape)

(1, 1)
(1, 1)
(1, 1)


In [ ]:
tf.print(b)

[[1]]


In [ ]:
# 1 by 2 (2차원 벡터)

In [ ]:
A = tf.Variable(np.array([ [1,4] ]),dtype= tf.float32 )
A

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1., 4.]], dtype=float32)>

In [ ]:
x = tf.Variable(np.array([ [1],
                          [4 ]]), dtype= tf.float32)
x

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [4.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
tf.print(b)

[[17]]


In [ ]:
print(A.shape)
print(x.shape)
print(b.shape)

(1, 2)
(2, 1)
(1, 1)


In [ ]:
# 2 by 2 (2차원 벡터)

In [ ]:
A = tf.Variable(np.array([ [1,4],
                           [9,5] ]), dtype = tf.float32)    #행열 맞추지 않으면 에러남(나중에 뭐가 잘 못 된것인지 찾기 힘들 수 있음)
A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 4.],
       [9., 5.]], dtype=float32)>

In [ ]:
x = tf.Variable(np.array([ [1],
                          [2] ]), dtype = tf.float32)
x

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
tf.print(b)

[[9]
 [19]]


In [ ]:
print(A.shape)
print(x.shape)
print(b.shape)

(2, 2)
(2, 1)
(2, 1)


In [ ]:
A = tf.Variable(np.array([ [1,4],
                          [9,5],
                          [4,0] ]),dtype = tf.float32 )
A

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[1., 4.],
       [9., 5.],
       [4., 0.]], dtype=float32)>

In [ ]:
x = tf.Variable(np.array([ [1],
                          [2] ]), dtype = tf.float32)
x

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
tf.print(b)

[[9]
 [19]
 [4]]


In [ ]:
print(A.shape)
print(x.shape)
print(b.shape)

(3, 2)
(2, 1)
(3, 1)


In [ ]:
# 4 by 2 (2차원 벡터)

In [ ]:
A = tf.Variable(np.array([ [1,4],
                           [9,5],
                          [4,0],
                          [6,1] ]), dtype = tf.float32)
A

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[1., 4.],
       [9., 5.],
       [4., 0.],
       [6., 1.]], dtype=float32)>

In [ ]:
x = tf.Variable(np.array([ [1],
                            [2] ]), dtype = tf.float32)
x

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
b

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 9.],
       [19.],
       [ 4.],
       [ 8.]], dtype=float32)>

In [ ]:
print(A.shape)
print(x.shape)
print(b.shape)

(4, 2)
(2, 1)
(4, 1)


In [ ]:
# 4 by 3 (3차원 벡터)

In [ ]:
A = tf.Variable( np.array([ [1,4,2],
                            [9,5,0],
                            [4,0,2],
                            [6,1,8] ]), dtype = tf.float32)
A

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[1., 4., 2.],
       [9., 5., 0.],
       [4., 0., 2.],
       [6., 1., 8.]], dtype=float32)>

In [ ]:
x = tf.Variable(np.array([ [1], 
                           [2],
                           [3] ]), dtype = tf.float32)
x

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [2.],
       [3.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
b

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[15.],
       [19.],
       [10.],
       [32.]], dtype=float32)>

In [ ]:
# 4 by 4 (4차원 벡터)

In [ ]:
A = tf.Variable(np.array ([ [1,4,2,0],
                            [9,5,0,0],
                            [4,0,2,4],
                            [6,1,8,3] ]), dtype = tf.float32)
A

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[1., 4., 2., 0.],
       [9., 5., 0., 0.],
       [4., 0., 2., 4.],
       [6., 1., 8., 3.]], dtype=float32)>

In [ ]:
x = tf.Variable(np.array([ [1], 
                           [2],
                           [3],
                           [4] ]), dtype = tf.float32)
x

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[1.],
       [2.],
       [3.],
       [4.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
tf.print(b)

[[15]
 [19]
 [26]
 [44]]


In [ ]:
# 4 by 5 (5차원 벡터)

In [ ]:
A = tf.Variable(np.array ([ [1,4,2,0,2],
                            [9,5,0,0,5],
                            [4,0,2,4,6],
                            [6,1,8,3,1] ]), dtype = tf.float32)
A

<tf.Variable 'Variable:0' shape=(4, 5) dtype=float32, numpy=
array([[1., 4., 2., 0., 2.],
       [9., 5., 0., 0., 5.],
       [4., 0., 2., 4., 6.],
       [6., 1., 8., 3., 1.]], dtype=float32)>

In [ ]:
x = tf.Variable(np.array([ [1], 
                           [2],
                           [3],
                           [4],
                           [5] ]), dtype = tf.float32)
x

<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]], dtype=float32)>

In [ ]:
b = tf.matmul(A,x)
tf.print(b)

[[25]
 [44]
 [56]
 [49]]


In [ ]:
# mat by mat

In [ ]:
A = tf.Variable (np.array([ [1,4,2,0],
                            [9,5,0,0],
                            [4,0,2,4],
                            [6,1,8,3] ]),dtype = tf.float32)
A

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[1., 4., 2., 0.],
       [9., 5., 0., 0.],
       [4., 0., 2., 4.],
       [6., 1., 8., 3.]], dtype=float32)>

In [ ]:
B = tf.Variable(np.array ([ [1,5,9],
                            [2,6,10],
                            [3,7,11],
                            [4,8,12] ]), dtype = tf.float32)
B

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.],
       [ 4.,  8., 12.]], dtype=float32)>

In [ ]:
tf.matmul(A,B)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 15.,  43.,  71.],
       [ 19.,  75., 131.],
       [ 26.,  66., 106.],
       [ 44., 116., 188.]], dtype=float32)>

In [ ]:
#Linear Equ

In [ ]:
A = tf.Variable(np.array([ [1,4,2,0],
                           [9,5,0,0],
                           [4,0,2,4],
                           [6,1,8,3] ]),dtype = tf.float32)
A

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[1., 4., 2., 0.],
       [9., 5., 0., 0.],
       [4., 0., 2., 4.],
       [6., 1., 8., 3.]], dtype=float32)>

In [ ]:
B = tf.Variable(np.array([ [15],
                           [19],
                           [26],
                           [44] ]), dtype = tf.float32)
B

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[15.],
       [19.],
       [26.],
       [44.]], dtype=float32)>

In [ ]:
x = tf.linalg.solve(A,B)
x

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.9999999],
       [2.0000002],
       [2.9999995],
       [4.       ]], dtype=float32)>

In [ ]:
#위의 결과 맞는지 검산 : Ax를 계산!

In [ ]:
tf.matmul(A,x)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[15.      ],
       [19.      ],
       [25.999998],
       [43.999996]], dtype=float32)>

In [ ]:
#좀 더 자세하게 계산하면 안될까?
# tf.float32 -> tf.float64

In [ ]:
A_long = tf.Variable(np.array([ [1,4,2,0], [9,5,0,0], [4,0,2,4] , [6,1,8,3] ]),
                dtype = tf.float64)
A_long
B_long = tf.Variable(np.array([ [15],  [19],  [26],  [44] ]), dtype = tf.float64)
B_long
x_long = tf.linalg.solve(A_long,B_long)
x_long

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[1.],
       [2.],
       [3.],
       [4.]])>

In [ ]:
#검산
tf.matmul(A_long, x_long)

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[15.],
       [19.],
       [26.],
       [44.]])>