# 학습 목표

- TensorFlow 2.0 간단 사용법

# NumPy Review

### 01) 0차원

In [1]:
import numpy as np

In [2]:
arr = np.array(10)
arr

array(10)

In [3]:
arr.shape

()

### 02) 1차원

In [4]:
arr = np.array([10])
arr.shape

(1,)

- 주의해야 할 것이 있는데 위의 (3, )에서 3은 3이라는 값이 들어간 것이 아닌 shape라는 것을 주의   
- 1차원에 3개의 값이 들어갔다는 것
- 즉, 1차원에 3개의 값(value)가 들어감

In [5]:
arr = np.array([1,2,3])
arr.shape

(3,)

### 03) 2차원

In [6]:
arr = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
])
arr.shape

(3, 3)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr = np.array([[10]])
arr.shape

(1, 1)

### 04) 다차원

In [11]:
arr = np.array([
  [          [1,2,3,4],
            [4,5,6,7],
            [8,9,10,11]
  ],
  [
            [11,10,9,8],
            [7,6,5,4],
            [4,3,2,1]
  ]
])
arr.shape

(2, 3, 4)

In [12]:
arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 4,  3,  2,  1]]])

In [11]:
arr = np.array(~~)
arr.shape

(2, 2, 3, 3)

In [12]:
arr

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [13]:
arr.shape

(2, 2, 3, 3)

# Tensor에 대해서 알아보자!!

In [13]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [14]:
tf.__version__

'2.8.0'

# Tensor 생성

<img src="img01/img_05.png">

<img src="img/img_06.png">

<img src="img01/img_07.png">

- []
    - List 생성

In [15]:
[1,3,5]

[1, 3, 5]

In [16]:
[
    [1, 3, 5],
    [2, 4, 6]
]

[[1, 3, 5], [2, 4, 6]]

In [17]:
[
    [
        [1, 2], 
        [3, 4]],
    [
        [5, 6], 
        [7, 8]
    ]
]

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

### Array 생성

- tuple이나 list 둘 다 np.array()로 씌어서 array를 만들 수 있음

In [18]:
arr = np.array([1,3,5])

In [19]:
arr.shape

(3,)

In [20]:
arr = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

In [21]:
arr.shape

(2, 3)

### Tensor 생성 : tf2에서는 쉽게 어레이처럼 왔다 갔다 하기 편해졌음

- tf.constant()
    - list -> Tensor

In [22]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

- tf.constant()
    - tuple -> Tensor

In [23]:
tf.constant(
    (
            (1,2,3),
            (4,5,6)
    )
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

- tf.constant()
    - Array -> Tensor

In [25]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [24]:
# 이런 스타일로 코드들이 종종 작성 된다
tensor = tf.constant(np.array([1,2,3]))
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

### Tensor에 담긴 정보 확인

<img src="img01/img_09.png">

- shape 확인

In [26]:
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [27]:
tensor.shape

TensorShape([3])

- data type 확인
* 주의: Tensor 생성 할 때도 data type을 정해주지 않기 때문에 원하지 않는 타입으로 지정될 수 있음!!!
* Data Type에 따라 모델의 무게나 성능 차이에도 영향을 줄 수 있으므로, 정확하게 확인이 필요함!!!!

In [29]:
tensor.dtype

tf.int32

- data type 정의

In [30]:
tensor = tf.constant([1,2,3], dtype = tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

- data type 변환
    - Numpy에서 astype()을 주었듯이, TensorFlow에서는 tf.cast를 사용

 TF2에서 사용되는 dtype종류들 : QUANTIZED_DTYPES
bfloat16
bool
complex128
complex64
double
float16
float32
float64
half
int16
int32
int64
int8
qint16
qint32
qint8
quint16
quint8
resource
string
uint16
uint32
uint64
uint8
variant

In [31]:
arr = np.array([1, 2, 3], dtype=np.float32)

In [32]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [33]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [35]:
tf.cast(tensor, dtype = tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

- Tensor에서 Numpy 불러오기
    - .numpy()

In [38]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

- Tensor에서 Numpy 불러오기
    - np.array()

In [39]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

type()를 사용하여 numpy array로 변환된 것 확인

In [ ]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
type(tensor.numpy())

numpy.ndarray

## 난수 생성

- Normal Distribution은 중심극한 이론에 의한 연속적인 모양   
- Uniform Distribution은 중심 극한 이론과는 무관하며 불연속적이며 일정한 분포

- numpy에서는 normal distribution을 기본적으로 생성
    - np.random.randn()

In [40]:
np.random.randn(10)

array([-1.05823346,  0.82925469, -0.25520664, -0.13019224,  0.70127437,
        0.65982777,  0.16325312, -3.06532646,  0.60673901,  0.66235253])

- tf.random.normal
    - TensorFlow에서 Normal Distribution

In [41]:
tf.random.normal([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 1.9221812 , -2.174183  ,  0.6943365 ,  0.8945974 ],
       [-0.5508161 ,  0.2787266 ,  0.6877298 , -0.13016503],
       [ 1.166269  , -1.8765106 ,  1.6119057 , -0.13747   ],
       [-0.28013834,  1.0234097 , -0.5166437 , -1.1994958 ]],
      dtype=float32)>

- tf.random.uniform
    - TensorFlow에서 Uniform Distribution

In [42]:
tf.random.uniform([4, 4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.5653033 , 0.23362756, 0.704062  , 0.04526985],
       [0.4911933 , 0.10220945, 0.58405364, 0.56941223],
       [0.8213786 , 0.622658  , 0.9874226 , 0.17992985],
       [0.40256107, 0.67304635, 0.15451527, 0.87724864]], dtype=float32)>

## Tensorflow 2.0의 이해

## Import modules

In [43]:
import tensorflow as tf

### 데이터 불러오기

In [44]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 1s 0us/step


### 네트워크 구조 정의

In [46]:
# 주의사항) 본인 데이터와 본인 최종 결과에 대해서 설계를 직접 해야함
model = tf.keras.models.Sequential(
[
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation = "softmax") # 데이터에 맞게 바뀌어야함
])

### Keras 모델 Compile

In [ ]:
Loss
<img src="img/img_01.png">

In [ ]:
Optimizer
<img src="img/img_02.png">

In [ ]:
metrics : 훈련을 모니터링을 하기 위한 지표
<img src="img/img_03.png">
<img src="img/img_04.png">

In [47]:
# 모델을 어떻게 돌릴지 세팅
model.compile( optimizer = "Adamax",
             loss = "sparse_categorical_crossentropy",
             metrics = ["accuracy"])

### 학습 수행

In [50]:
model.fit(x_train, y_train, epochs=3)

Epoch 1/3
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4278 - accuracy: 0.8818
Epoch 2/3
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2423 - accuracy: 0.9306
Epoch 3/3
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1917 - accuracy: 0.9454


### 학습 결과 테스트

In [51]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.1505 - accuracy: 0.9551


[0.15050680935382843, 0.9550999999046326]